import { AdvanceRowData } from "@/src/types/advance-table";
import { ColDef } from "ag-grid-community";

export const advanceColDefs: ColDef<AdvanceRowData>[] = [
  { headerName: "ID", field: "id", checkboxSelection: true },
  { headerName: "Date", field: "date" },
  { headerName: "Amount", field: "amount" },
  { headerName: "Reason", field: "reason" },
  { headerName: "Action", field: "action" },
  { headerName: "Status", field: "status" },
];

export const advanceRowData: AdvanceRowData[] = [
  {
    id: "1",
    date: "2024-02-14",
    amount: 50,
    reason: "I need buy a new course for learn react",
    action: "Approved",
    status: "Paid",
  },
  {
    id: "2",
    date: "2024-05-14",
    amount: 100,
    reason: "I need buy a new car",
    action: "Reject",
    status: "-",
  },
  {
    id: "3",
    date: "2024-08-14",
    amount: 500,
    reason: "I need replace my laptop",
    action: "Approved",
    status: "not yet",
  },
  {
    id: "4",
    date: "2024-02-14",
    amount: 50,
    reason: "I need buy a new course for learn react",
    action: "Approved",
    status: "Paid",
  },
  {
    id: "5",
    date: "2024-05-14",
    amount: 100,
    reason: "I need buy a new car",
    action: "Reject",
    status: "-",
  },
  {
    id: "3",
    date: "2024-08-14",
    amount: 500,
    reason: "I need replace my laptop",
    action: "Approved",
    status: "not yet",
  },
  {
    id: "6",
    date: "2024-02-14",
    amount: 50,
    reason: "I need buy a new course for learn react",
    action: "Approved",
    status: "Paid",
  },
  {
    id: "7",
    date: "2024-05-14",
    amount: 100,
    reason: "I need buy a new car",
    action: "Reject",
    status: "-",
  },
  {
    id: "8",
    date: "2024-08-14",
    amount: 500,
    reason: "I need replace my laptop",
    action: "Approved",
    status: "not yet",
  },
  {
    id: "9",
    date: "2024-02-14",
    amount: 50,
    reason: "I need buy a new course for learn react",
    action: "Approved",
    status: "Paid",
  },
  {
    id: "10",
    date: "2024-05-14",
    amount: 100,
    reason: "I need buy a new car",
    action: "Reject",
    status: "-",
  },
  {
    id: "11",
    date: "2024-08-14",
    amount: 500,
    reason: "I need replace my laptop",
    action: "Approved",
    status: "not yet",
  },
];
